# Generated by Django 4.2.5 on 2023-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraf', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('poza', models.ImageField(null=True, upload_to='cumpar_carti/static/IMG_parafraf')),
            ],
            options={
                'verbose_name': 'Paragraf',
                'verbose_name_plural': 'Paragrafe',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
