# Generated by Django 4.2.5 on 2023-11-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achizitii', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraf',
        ),
    ]
