# Generated by Django 4.2.5 on 2023-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achizitii', '0002_delete_paragraf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacte',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paragraf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=150)),
                ('paragraf', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('poza', models.ImageField(null=True, upload_to='cumpar_carti/static/IMG_parafraf')),
            ],
            options={
                'verbose_name': 'Paragraf',
                'verbose_name_plural': 'Paragrafe',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
