# Generated by Django 4.2.5 on 2023-11-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achizitii', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraf',
            name='poza',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
